Eld 557 env variable en la app
DumaxST/ELD-App-New pull request #29
Opened 2024-01-12 21:18 UTC by DGUZMANCdeveloper

2024-01-16 04:27 UTC, GuismoCabrera requested changes
1. El archivo .env NO debería de subirse ni actualizarce en el .gitignore
2. La variable de entorno DEBE de llamarse ELD_API ( a menos que me digas que forsosamente se tiene que llamar de otro modo)

3. Me loggue al API con "Consolidated Carrier" , USR: "Edgard", PASS: "123456789" y si pude entrar **( LO CUAL ME CAUSA UNA ALERTA DADO QUE LA VARIABLE DE ENTORNO NO ESTA GUARDADA EN GITHUB COMO  **EXPO_PUBLIC_API_URL** POR LO QUE EN TEORÍA LA AUTENTICACIÓN ME DEBÍO DE HABER MARCADO ERROR Y NO DEJARME ENTRAR )** 

4.- Dispare un par de eventos desde la cuenta de edgar y no me los guardo en el logbook; En realidad el logBook se quedo en blanco. Espero y supongo que esto fue dado que el GET respondio un 404 dado a que estaba apuntando a la variable de entorno INEXISTENTE en github; Por lo mismo, si la variable de entorno no existe, no entiendo por que me dejo pasar. 

5.-  Si mi teoría de que el GET respondio un 404 es correcta, no se desplego ningun msj de error por lo que no esta bien manejado ese escenarío. Si responde 404, debería de marcar un error en la API. 

------------------------------------------------------------------------------------------
Para aprobar este review, se tendra que: 

1. Borrar el archivo .env  del repo de github y forzar que este archivo no se suba ni actualice mediante el .gitignore

2. La variable de entorno deberá de ser llamada " ELD_API " ( a menos que me pidas que la nombre de otro modo por causas forsosas al codigo y/o tecnología ) 

3. La app deployada deberá:
- Poderse logear con credenciales de EDGAR
- Poder disparar un par de eventos y que estos se registren en la DB 
- Poder visualizar los eventos disparados mediante el LOGBOOK
- Manejar el error 404 y/o cualquier otro tipo de error mediante un msj en la aplicación.

2024-01-16 04:27 UTC, GuismoCabrera commented on data/axiosConfig.js
Tienes que tener una UNICA variable de entorno. NO puedes tener 3 como te comente en un comentario anterior.
El hecho de que manejemos una UNICA variable de entorno, es para que una vez que GitHub deploye el APP a expo, esta SIEMPRE este apuntando al API deployada en el ambiente de desarrollo.

Imagina el caso en el que se te olvide hacer el cambio de "EXPO_DEV_API_URL" a "EXPO_PUBLIC_API_URL" , se pierde el punto de tener una variable dado que al momento de hacerse el deploy, github no encontraría "EXPO_DEV_API_URL" y fallaría

2024-01-16 04:27 UTC, GuismoCabrera commented on .env
El hecho de agregar .env al .gitignore supone que no se debería de subir ni actualizar el archivo .env en el repo de github

2024-01-16 09:24 UTC, DGUZMANCdeveloper commented on .env
Hola Isaias, una disculpa por mi mal entendimiento en este issue, ya se ha logrado ignorar el archivo .env desde el .gitignore para esto también se hizo el cambio a ELD_API para esto queda una duda, tu variable de entorno de github debe conectarse también?, pero para esto se tiene que conectar con algún arreglo/entorno {{ELD_API}}, para esto si pediría poder agregarla conjuntamente ya que no tengo acceso a las variables de entorno del proyecto y tengo entendido hay que declararla en algún yml, podriamos abrir otro issue para ese caso.

![Mi video](https://github.com/DumaxST/ELD-App-New/assets/115447488/900410c2-db3a-4adb-b26e-fcbd2993f912)

2024-01-16 09:26 UTC, DGUZMANCdeveloper commented on data/axiosConfig.js
Acabo de agregar 2 variables con el mismo nombre, una para mi entorno de desarrollo y uno a Produccion, pero ya esta como ELD_API y lo que se haga en el .env no importa ya que no se incluye en los archivos del proyecto
![Mi video](https://github.com/DumaxST/ELD-App-New/assets/115447488/1524254a-9107-428f-b073-7e1cf4f0f84a)

2024-01-26 04:34 UTC, GuismoCabrera reviewed
ok

2024-01-26 04:34 UTC, GuismoCabrera approved these changes

2024-01-26 04:42 UTC, GuismoCabrera approved these changes
ok

2024-01-26 15:09 UTC, merged